In [ ]:
# Global COVID-19 Surveillance & Epidemiological Intelligence Dashboard

## Author
Oumar Mahamat

## Objective
Analyze global COVID-19 surveillance data using Python and Power BI to generate epidemiological insights and an interactive dashboard.

In [3]:
# ==========================================
# Import Libraries
# ==========================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [4]:
df = pd.read_csv(r"C:\Profile\Data\raw_data.csv")

In [5]:
df.head()

,Date_reported,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths,Case Fatality Rate
0,1/5/2020,Armenia,EURO,NaN,0,NaN,0,NaN
1,1/12/2020,Armenia,EURO,NaN,0,NaN,0,NaN
2,1/19/2020,Armenia,EURO,NaN,0,NaN,0,NaN
3,1/26/2020,Armenia,EURO,NaN,0,NaN,0,NaN
4,2/2/2020,Armenia,EURO,NaN,0,NaN,0,NaN

In [6]:
df.shape

(80160, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80160 entries, 0 to 80159
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date_reported       80160 non-null  object
 1   Country             80160 non-null  object
 2   WHO_region          74148 non-null  object
 3   New_cases           51795 non-null  float64
 4   Cumulative_cases    80160 non-null  int64
 5   New_deaths          36961 non-null  float64
 6   Cumulative_deaths   80160 non-null  int64
 7   Case Fatality Rate  36580 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 4.9+ MB

In [8]:
df.columns

Index(['Date_reported', 'Country', 'WHO_region', 'New_cases',
       'Cumulative_cases', 'New_deaths', 'Cumulative_deaths',
       'Case Fatality Rate'],
      dtype='object')

In [9]:
df.describe()

          New_cases  Cumulative_cases    New_deaths  Cumulative_deaths
count  5.179500e+04      8.016000e+04  36961.000000       8.016000e+04
mean   1.504446e+04      2.196251e+06    192.505993       2.267150e+04
std    2.352064e+05      8.928053e+06   1007.581380       8.974365e+04
min   -6.507900e+04      0.000000e+00  -3432.000000       0.000000e+00
25%    8.000000e+00      7.749750e+03      0.000000       4.600000e+01
50%    1.410000e+02      6.543500e+04      5.000000       7.980000e+02
75%    1.933000e+03      7.032280e+05     49.000000       8.620000e+03
max    4.047548e+07      1.034368e+08  47687.000000       1.238215e+06

In [10]:
df.isnull().sum()

Date_reported             0
Country                   0
WHO_region             6012
New_cases             28365
Cumulative_cases          0
New_deaths            43199
Cumulative_deaths         0
Case Fatality Rate    43580
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)